@clientApi = http://localhost:8080
@validationApi = http://localhost:8081


### Register

post {{clientApi}}/user
Content-Type: application/json

{
    "Name": "john Doe",
    "Email": "john.doe@fake.com"
}


### Validation API
GET {{validationApi}}/api/validate
Accept: application/json
